# Generated by Django 5.2.8 on 2025-11-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_streak_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="streak_count",
            field=models.IntegerField(default=0),
        ),
    ]
